name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw
        
      - name: Replace Maven Credentials
        run: |
          sed -i 's/USERNAME/${{ secrets.USERNAME }}/g' .github/settings.xml
          sed -i 's/PASSWORD/${{ secrets.PASSWORD }}/g' .github/settings.xml

      - name: Install
        run: ./mvnw clean install -s .github/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.github.token }}
